spring:
  datasource:
    url: jdbc:mysql://43.138.206.206:3306/liaoribin?characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: liaoribin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true